export const categories = [
  {
    id: '1',
    title: 'Электроника',
    keyWord: 'electronics',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '2',
    title: 'Одежда',
    keyWord: 'category2',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '3',
    title: 'Обувь',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '4',
    title: 'Дом и сад',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '5',
    title: 'Детское',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '6',
    title: 'Здоровье',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '7',
    title: 'Канцелярия',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '8',
    title: 'Спорт и отдых',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '9',
    title: 'Ремонт и строительство',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '10',
    title: 'Еда',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '11',
    title: 'Аптека',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '12',
    title: 'Зоотовары',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '13',
    title: 'Книги',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '14',
    title: 'Туризм',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '15',
    title: 'Автотовары',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '16',
    title: 'Мебель',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '17',
    title: 'Творчество',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '18',
    title: 'Украшения',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '19',
    title: 'Аксессуары',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
  {
    id: '20',
    title: 'Игры и консоли',
    keyWord: 'category3',
    image: require('../images/mock/electronics.png'),
  },
];

export const products = [
  {
    id: '1',
    title: 'Поло',
    image: require('../images/mock/tshirt.png'),
    price: 10000,
    priceWithDiscount: 6999,
    brand: 'Ralpf Loren',
    reviewsCount: 12,
    totalScore: 3,
  },
  {
    id: '2',
    title: 'Бензопила',
    image: require('../images/mock/tshirt.png'),
    price: 25000,
    brand: 'Husqvarna AB',
    reviewsCount: 1442,
    totalScore: 4.9,
  },
  {
    id: '3',
    title: 'iPhone 15 pro',
    image: require('../images/mock/tshirt.png'),
    price: 122000,
    priceWithDiscount: 99999,
    brand: 'Apple',
  },
  {
    id: '4',
    title: 'Без бренда и отзывов',
    image: require('../images/mock/tshirt.png'),
    price: 4999,
  },
  {
    id: '5',
    title: 'Длинное наименование товара',
    image: require('../images/mock/tshirt.png'),
    price: 500,
    priceWithDiscount: 499,
    reviewsCount: 1,
    totalScore: 1,
  },
  {
    id: '6',
    title: 'Очень длинное наименование товара',
    image: require('../images/mock/tshirt.png'),
    price: 99,
  },
  {
    id: '7',
    title:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod maiores architecto exercitationem quo consectetur. Tempore vitae excepturi cumque odit quae, id earum adipisci libero obcaecati magnam itaque voluptas unde accusamus?',
    image: require('../images/mock/tshirt.png'),
    price: 7900,
  },
  {
    brand: 'Tovar',
    id: '8',
    title: 'Товар',
    image: require('../images/mock/tshirt.png'),
    price: 10,
    reviewsCount: 2,
    totalScore: 4,
  },
];

export const CartItems = [
  {
    id: '1',
    title: 'Поло',
    image: require('../images/mock/tshirt.png'),
    price: 10000,
    quantity: 2,
  },
  {
    id: '2',
    title: 'Бензопила',
    image: require('../images/mock/tshirt.png'),
    price: 25000,
    quantity: 1,
  },
  {
    id: '3',
    title: 'iPhone 15 pro',
    image: require('../images/mock/tshirt.png'),
    price: 122000,
    quantity: 1,
  },
  {
    id: '4',
    title: 'Без бренда и отзывов',
    image: require('../images/mock/tshirt.png'),
    price: 4999,
    quantity: 3,
  },
  {
    id: '5',
    title: 'Длинное наименование товара',
    image: require('../images/mock/tshirt.png'),
    price: 500,
    quantity: 1,
  },
  {
    id: '6',
    title: 'Очень длинное наименование товара',
    image: require('../images/mock/tshirt.png'),
    price: 99,
    quantity: 1,
  },
  {
    id: '7',
    title:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod maiores architecto exercitationem quo consectetur. Tempore vitae excepturi cumque odit quae, id earum adipisci libero obcaecati magnam itaque voluptas unde accusamus?',
    image: require('../images/mock/tshirt.png'),
    price: 7900,
    quantity: 1,
  },
];

export const promoPicture = require('../images/mock/promo.png');
export const promoPictureSecond = require('../images/mock/promo2.png');
