export enum emoji {
  smileFace = '😀',
  halloween = '🎃',
  joy = '😂',
  heart = '❤️',
  thumbsUp = '👍',
  dislike = '👎',
  sadFace = '😢',
  star = '⭐',
  fire = '🔥',
  scream = '😨',
  clown = '🤡',
  sleep = '😴',
  bone = '🦴',
  devil = '👺',
  boom = '💥',
  wave = '👋',
  ghost = '👻',
  pray = '🙏',
  callMe = '🤙',
  brain = '🧠',
}
